#!/usr/bin/env bash
# Type-checks src/scripts/ and bundles it into publish.js, the one file
# Obsidian Publish loads. Needs esbuild and tsc (brew install esbuild typescript).
# The vault data baked in by build-index.js lives in src/scripts/baked-data.ts,
# so a plain rebuild keeps it.
set -euo pipefail
cd "$(dirname "$0")"

tsc -p .

esbuild src/scripts/index.ts \
	--bundle \
	--format=iife \
	--target=es2020 \
	--banner:js="// Generated by build-publish.sh from src/scripts/. Do not edit." \
	--outfile=publish.js \
	--log-level=warning

echo "publish.js built ($(wc -c < publish.js | tr -d ' ') bytes)"
